name: typed_mock
version: 0.0.4
author: Dart Team <misc@dartlang.org>
description: A library for mocking classes using Mockito-like syntax
homepage: http://www.dartlang.org
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
