name: mock
version: 0.11.0+2
author: Dart Team <misc@dartlang.org>
description: A library for mocking classes
homepage: https://pub.dartlang.org/packages/mock
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  matcher: '>=0.10.0 <0.12.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
