name: async_helper
version: 0.9.0
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
 Async_helper is used for asynchronous tests that do not want to
 make use of the Dart unittest library - for example, the core
 language tests.
 Third parties are discouraged from using this, and should use
 the facilities provided in the unittest library.
environment:
  sdk: ">=0.8.10+6 <2.0.0"
